project:
  title: "Отчёт по лабораторной работе"
  subtitle: "Имитационное моделирование"
  author: "Алина Тарасова"
  date: 2026-02-20

engine: julia
julia:
  exeflags: ["--project=../project"]

format:
  html:
    toc: true
    toc-depth: 3
    code-fold: false
  pdf:
    toc: true
    toc-depth: 3
    include-in-header:
      - preamble.tex
